### ISSUE TITLE
Feature request: File uploads from mobile

### ISSUE THREAD

**Issue by ellotheth** [wantguns/bin#19]
I've been using `bin` as a personal imgur replacement, so I'm uploading mostly images and videos. It works *great* in a desktop browser, but I haven't figured out how to upload from my (Android) phone, because the mobile browsers I use don't support copy/paste for media files. Would it be possible to have some sort of upload mechanism for mobile?

**Comment by wantguns** [comment]
hi @ellotheth thanks for trying bin out !
i had a very lame reason for not keeping a specific button for uploading files. this project needs a long awaited turnover as well (checkout [projects](https://github.com/users/wantguns/projects/1)), but i don't see myself starting on it anytime soon. 
but for a small feature request like yours, its pretty easy to implement. we'll need to hack the existing css a bit and add a specific button which performs the upload logic. i'll see to it if i get time in the weekend, at the same time please feel free to hack it yourself
