### ISSUE TITLE
Provide Cache-Control headers

### ISSUE THREAD

**Issue by NoraCodes** [WantGuns/bin#2]
Currently, the paste content, as well as JS and CSS content, isn't sent along with a `Cache-Control` header; ideally, we should provide the following:

- `max-age=[large number]` to make sure clients don't have to constantly re-request pastes, CSS, and JS, which change never or rarely. Perhaps a value of 1 week or so, 604800s.
- `stale-while-revalidate=[smaller number]` to allow clients to re-use cached, stale content until they can revalidate that it hasn't changed. Perhaps a value of 1 day or so, 86400s.

Additionally, _only for raw pastes_, we should include the `immutable` directive so that browsers do not attempt to refresh the contents of the pastes, which are immutable and don't change.

**Comment by WantGuns** [comment]
Appreciate the input !
Gonna work on it after I get time.

**Comment by WantGuns** [comment]
@NoraCodes please check the commit out and let me know if the cache-control headers are added properly. Will merge it to master then !

**Comment by NoraCodes** [comment]
Looks great aside from one comment! Thank you!
