### ISSUE TITLE
Missing builds for v2.3.0

### ISSUE THREAD

**Issue by Tofee** [wantguns/bin#21]
Hi !

I see there is new release v2.3.0 since August 18th; however I can't see any binary attached to this release, only the source code.
Would it be possible to attach them please? I'm mainly interested in the aarch64 build.

And thanks for the great work!

**Comment by wantguns** [comment]
thanks for raising the issue, i missed out on adding the binaries. i've added them now and for future references to this issue, people can find [build artifacts](https://github.com/wantguns/bin/actions/runs/5904203034) from the latest github action run (although i think they get deleted after some time).

thanks again !
