### ISSUE TITLE
feature request: tabulation key support

### ISSUE THREAD

**Issue by sinux-l5d** [WantGuns/bin#8]
Hi,

Would it be possible to enhance the web client to support the key 'tab' to indent code?
At the time of writing, it selects the adress bar on my browser.

**Comment by sinux-l5d** [comment]
I'm working on it, I will submit a merge request soon

**Comment by WantGuns** [comment]
Hey !

I was not aware people are typing into the *paste*bin xD.
Nevertheless, this is definitely required.

**Comment by WantGuns** [comment]
whoops didnt see the new comment, please carry on.

**Comment by sinux-l5d** [comment]
> Hey !
> 
> I was not aware people are typing into the _paste_bin xD. Nevertheless, this is definitely required.

Well, it won't be used often but when I first tried the webservice, I just typed code in the webclient side

**Comment by WantGuns** [comment]
Fixed in #9
